name: VideoProcessingServiceRelease

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authenticate Docker with Google Cloud
      run: gcloud auth configure-docker

    - name: Run build script
      run: bash scripts/build-video-processing-service.sh
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    - name: List Docker images
      run: docker images

    - name: Run deployment script
      run: bash scripts/deploy-video-processing-service.sh
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}